### ISSUE TITLE
Support focusing multiple subprojects

### ISSUE THREAD

**Issue by ZakTaccardi** [dropbox/focus#19]
We have have multiple subprojects per feature. So let's say we have a "Sign In" feature, and have tagged a number of subprojects to be under that feature.

Would be nice to allow a developer working on the "Sign In" feature to run:

```shell
./gradlew signInFocus
``` 

That would "focus" all subprojects with that tag

**Comment by rharter** [comment]
The way you'd achieve this is by creating a module that only has dependencies.  You don't even need to apply any plugins, just a `build.gradle` file that only creates a configuration and adds dependencies to it should be enough be enough.

```groovy
// sample/signin/build.gradle

configurations.create("deps")

dependencies {
  deps(project(":sample:lib1b"))
  deps(project(":sample:lib2b"))
}
```

Add that project to your `settings-all.gradle` file and you should be good.  It shouldn't really add much to your build time, if anything, since it doesn't apply anything and will mostly be skipped for configuration, but you'll be able to `./gradlew :sample:signin:focus` and focus on only the dependencies of that fake module.
