### ISSUE TITLE
What is the profit from Focus in the android application

### ISSUE THREAD

**Issue by Turalllb** [dropbox/focus#22]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/28982210/163025876-7df2e527-880f-4da6-8210-5cd7ab546874.png">

Tell me how Focus can help me, if I write an android application and every time I launch the app module, does gradle work for a long time? It seems nothing, because my app module in gradle has all the other modules as dependencies. And if I focus on a particular module, make changes to it and try to compile the app module, I get an error like this : Project with path ':chat' could not be found in project ':app'

**Comment by rharter** [comment]
You're right, that that's not the setup Focus is meant to help.

If you spend a lot of time working in your core module, for instance, you could use focus to only have to build that as you're working.  Presumably you're using tests or a sample app so that you can do that work without requiring the entire app in order to verify your work.

**Comment by Turalllb** [comment]
thanks for the answer
